<?php

namespace Seb\BadgeBundle\Repository;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $user
     * @param $action
     * @param $action_count
     * @return mixed
     * @internal param $user_id
     */
    public function findWithUnlockForAction($user, $action, $action_count)
    {
        return $this->createQueryBuilder('b')
            ->where('b.actionName = :action_name')
            ->andWhere('b.actionCount = :action_count')
            ->andHaving('u.user = :user_id OR u.user IS NULL')
            ->leftJoin('b.unlocks', 'u')
            ->select('b, u')
            ->setParameters([
                'action_count' => $action_count,
                'action_name'   => $action,
                'user_id' => $user->getId(),
            ])
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * Find all badges unlocked by a specific user
     *
     * @param $user_id
     */
    public function findUnlockedFor($user_id)
    {
        return $this->createQueryBuilder('b')
            ->join('b.unlocks', 'u')
            ->where('u.user = :user_id')
            ->setParameter('user_id', $user_id)
            ->getQuery()
            ->getResult();
    }
}
